config/routes.rb
Rails.application.routes.draw do
  resources :qols do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  devise_for :users
  resources :users, only: [:show]
  root 'qols#index'


  
  resources :maps, only: [:index]

end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :qol
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :qol
  belongs_to :user

  validates_uniqueness_of :qol_id, scope: :user_id
end

app/models/qol.rb
class Qol < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  geocoded_by :address
    after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :qols, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 

         has_many :likes, dependent: :destroy
         has_many :liked_qols, through: :likes, source: :qol

         has_many :comments, dependent: :destroy

         def already_liked?(qol)
          self.likes.exists?(qol_id: qol.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    qol = Qol.find(params[:qol_id])
    comment = qol.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(qol_id: params[:qol_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(qol_id: params[:qol_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/qols_controller.rb
class QolsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  

  def index
    if params[:search] == nil
      @qols= Qol.all
    elsif params[:search] == ''
      @qols= Qol.all
    else
      #部分検索
      @qols = Qol.where("food LIKE ? ",'%' + params[:search] + '%')
    end
      @qols = @qols.page(params[:page]).per(3)
      @rank_qols = Qol.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
  end
   



  def new
    @qol = Qol.new
  end


  def create
    qol = Qol.new(qol_params)

    qol.user_id = current_user.id

    if qol.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @qol = Qol.find(params[:id])
    @comments = @qol.comments
    @comment = Comment.new
  end

  def edit
    @qol = Qol.find(params[:id])
  end

  def update
    qol = Qol.find(params[:id])
    if qol.update(qol_params)
      redirect_to :action => "show", :id => qol.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    qol = Qol.find(params[:id])
    qol.destroy
    redirect_to action: :index
 end


  private
  def qol_params
    params.require(:qol).permit(:food, :cost, :coupon, :place, :image, :address, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/qols_helper.rb
module QolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
 
    <title>Yasumesi2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    </head>
    <body>
    <section id="all-block">
    <!-- Bootstrap 導入 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="module" src="application.js">

    <% if user_signed_in? %>

    <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
  <% end %>
  


  
  
  <!-- Bootstrap CSS -->
   
  <!-- Bootstrap Javascript(jQuery含む) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  <header>
  <%= render 'partial/navbar' %>
  <ul>
  
 
  </ul>
 
</header>



  
    <span id="page-top">
    <a href="#wrap">
      <%= image_tag asset_path('scroll.png' ), data: {"turbolinks"=>false}, class: "allow" %>
    </a>
  </span>
  <%= yield %>
    <div class="footer-box">
    <span>© 学食</span>
    </div>
   
  
</section>
</body>
</html>

app/views/partial/_navbar.html.erb
<div class="nav">
    <ul class="clearfix">
   
        <li><a href="/qols/new"><span class="letter" data-letter="新規投稿">新規投稿</span></a></li>

      
        <li class="scroll" id="scroll"><a href="#box1"><span class="letter" data-letter="検索する">検索する</span></a></li>
     
        <div class="trans-rotate">
        <li class="logo"><a href="/qols"> <%= image_tag 'rogo1.png',  size:"100×70" %></a></li>
        </div>
        
        <li><a href="#"><span class="letter" data-letter="ランキング">ランキング</span></a></li>
        
        
        <% if user_signed_in? %>
            <li><a href="/users/<%= current_user.id %>"><span class="letter" data-letter="マイページ">マイページ</span></a></li>
        <% else %>
            <li><a href="/users/sign_in"><span class="letter" data-letter="マイページ">マイページ</span></a></li>
        <% end %>
    </ul>
</div>
<!-- /#nav --></div>
<div id="article">
<!-- /#article --></div>

app/views/qols/edit.html.erb
<%= form_for @qol do |f| %>
  <div class="field">
  <%= f.label :shop_name %>
  <%= f.text_field :food, :size => 30 %>
</div>

<div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

<div class="field">
  <%= f.label :cost %>
  <%= f.text_field :cost, :size => 30 %>
</div>


<div class="field">
  <%= f.label :coupon %>
  <%= f.text_field :coupon, :size => 10 %>
</div>

<div class="field">
  <%= f.label :place %>
  <%= f.text_area :place, :size => "30x2" %>
</div>

<p>
<%= f.label :address %>
<%= f.text_field :address, size: "50x1" %>
</p>

<div class="field">
     
<%= f.text_field :latitude,:value =>"緯度", id: :lat, :placeholder => "緯度" %>
</div>

<div class="field">

<%= f.text_field :longitude,:value =>"経度", id: :lng, :placeholder => "経度" %>
</div>










<h2>gmap</h2>
<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display">何かが表示される、、、、！</div>

<div id='map'></div>

<style>
#map {
height: 600px;
width: 600px;
}
</style>

<script>
let map

function initMap(){
geocoder = new google.maps.Geocoder()

map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: 40.7828, lng:-73.9653},
  zoom: 12,
});

marker = new google.maps.Marker({
  position:  {lat: 40.7828, lng:-73.9653},
  map: map
});
}

let geocoder

function codeAddress(){
let inputAddress = document.getElementById('address').value;

geocoder.geocode( { 'address': inputAddress}, function(results, status) {
  if (status == 'OK') {
    map.setCenter(results[0].geometry.location);
    var marker = new google.maps.Marker({
        map: map,
        position: results[0].geometry.location
    });
    display.textContent = "検索結果：" + results[ 0 ].geometry.location

  } else {
    alert('該当する結果がありませんでした：' + status);
  }
});   
}


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
  <%= f.submit "編集する" %>
<% end %>

app/views/qols/index.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">ちょっと待ってね</p>
    </div>
  </div>
</div>



  <div class="first-block">
   <div class=top_slide>
      <div class=gakusyoku>
        <%= image_tag 'onigiri8.png', size:"500×500" %>
      </div>
      <div class="wrapper">
      
          <div class="cols">
          
            <div class="col" ontouchstart="this.classList.toggle('hover');">
            
              <div class="container">

                  <div class="front">
                  <h2>一番人気の投稿</h2>
                    <div class="slide">
                    
                      <%= image_tag 'sample1.jpeg' %>
                      <%= image_tag 'sample2.jpeg' %>
                      <%= image_tag 'sample3.jpeg' %>
                    </div>
                  </div>
            
                  <div class="back">
                    <div class="inner">
                      <h2>○○ラーメン</h2>
                      <p>値段：７００円</p>
                      <p>クーポン内容：替え玉無料</p>
                      <p>アクセス：横浜駅徒歩2分</p>
                      <a href=”https://www.chuo-u.ac.jp/” target=”_blank”>https://www.chuo-u.ac.jp/</a>
                    </div>
                  </div>

              </div>
            </div>
          </div>
      </div>
    </div>
</div>

<div class="second-block">

  
    <div class="box">
      <h2>投稿を検索</h2>
    </div>

    <%= form_tag({controller:"qols",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    <% end %>

</div>

<h2>投稿一覧</h2>
<%= page_entries_info @qols %>

<div class="qols-container">
  <div class="card-media">
      <% @rank_qols.each do |t| %>
        <div class="qol">

            <div class="main-box">

                <div class="left-container">
                  <%= image_tag t.image_url, size: "250x200" if t.image? %>
                </div>

                <div class="right-container">
                  <div class="card-media-body">
                      <p>店名 : <%= t.food %><p>
                      <p>値段 : <%= t.cost %><p>
                      <p>クーポン内容 : <%= t.coupon %></p>
                      <p>アクセス : <%= t.place %></p>
                      <p>住所 : <%= t.address %></p>
                      
                      <%= t.created_at.to_s(:datetime_jp) %>
                   
                      <div class="card-media-body-supporting-bottom card-media-body-supporting-bottom-reveal">
                     
                    　　　<%= link_to "詳細へ", qol_path(t.id) %>
                    　</div>
                    
                 
              
                    <% if user_signed_in? %>
                      <% if current_user.already_liked?(t) %>
                          <%= link_to qol_like_path(id: t.id, qol_id: t.id), method: :delete do %>
                            <i class="fas fa-heart"></i><%= t.likes.count %>
                          <% end %>
                        <% else %>
                          <%= link_to qol_likes_path(id: t.id, qol_id: t.id), method: :post do %>
                            <i class="far fa-heart"></i><%= t.likes.count %>
                          <% end %>
                      <% end %>
                    <% else %>
                      <i class="far fa-heart"></i><%= t.likes.count %>
                    <% end %>

                    <% if user_signed_in? && current_user.id == t.user_id %> 
                      <%= link_to "編集する", edit_qol_path(t.id) %>
                      <%= button_to "削除する", qol_path(t.id), method: :delete %>
                    <% end %>

                  </div>
                </div>

            </div>
          </div>
          
      <% end %>

     </div>
    </div>
    <%= paginate @qols %>
  
    <div class="map">
      <div class="mapinner">
        <div id='map'></div>

        <style>
        #map {
          height: 400px;
          width: 720px;
        }
        </style>
        
        <!-- js部分 -->
        <script>
            function initMap() {
        
              //初期表示位置
              let latlng = new google.maps.LatLng(38.60, 139.5);
              //デザイン
              let styles = [
                  {
                    stylers: [
                    { "saturation": 0 },
                    { "lightness": 0 }
                    ]
                  }
                  ];
        
              let map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 5.5,
                  styles: styles,
                  center: latlng
              });
              let transitLayer = new google.maps.TransitLayer();
              transitLayer.setMap(map);
        
              //複数マーカー ここから
              <% @qols.each do |post|%>
                ( function() { 
                  let markerLatLng = new google.maps.LatLng({lat: <%= post.latitude %>, lng: <%= post.longitude %>}); // 緯度経度のデータ作成
                  let marker = new google.maps.Marker({ 
                    position: markerLatLng, 
                    map: map 
                  });
            　　　//マーカーをクリックしたとき、詳細情報を表示
                  let infowindow = new google.maps.InfoWindow({
                    position: markerLatLng,
                    content: "<a href='<%= qol_url(post.id) %>' target='_blank'><%= post.food %></a>"
                  }); //ここで詳細ページへのリンクを表示させる
                  marker.addListener('click', function() {
                    infowindow.open(map, marker);
                  });
        
              })();
              <% end %>
              //複数マーカー ここまで  
          }
        </script>
        
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
      </div>
    </div>

    
    

  
   
  


    
   

app/views/qols/new.html.erb
<div id="loading">
  <div id="loading_box">
    <div class="loading-one animation_loading">
      <p class="loading-txt">ちょっと待ってね</p>
    </div>
  </div>
</div>

<div class="new-block">

<h3>新規投稿</h3>
<%= form_for @qol do |f| %>
  
  <div class="field">
      
      <%= f.file_field :image %>
  </div>

  
  <div class="field">
    <%= f.text_field :food, :size => 30, :placeholder => "お店の名前" %>
  </div>

  

  <div class="field">

    <%= f.text_field :cost, :size => 30, :placeholder => "値段" %>
  </div>


  <div class="field">

    <%= f.text_field :coupon, :size => 10, :placeholder => "クーポン内容" %>
  </div>

  <div class="field">

    <%= f.text_field :place, :size => 30, :placeholder => "アクセス" %>
  </div>
 
  <div class="field">

      <%= f.text_field :address, :size => 50, :placeholder => "住所" %>
  </div>
  
  <div class="field">
     
      <%= f.text_field :latitude,:value =>"緯度", id: :lat, :placeholder => "緯度" %>
  </div>

  <div class="field">
 
      <%= f.text_field :longitude,:value =>"経度", id: :lng, :placeholder => "経度" %>
  </div>

 
 
  <div class="field1">
    <%= f.submit "投稿する！" %>
  </div>

<% end %>

<h2>Map</h2>

<input id="address" type="textbox" value="永井">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,

  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true // ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
    

<%= link_to "安飯一覧に戻る", qols_path %>
</div>

app/views/qols/sanple.html.erb
<div class="container">
  
<div class="card-media">
  <!-- media container -->
  <div class="card-media-object-container">
    <div class="card-media-object" style="background-image: url(https://s9.postimg.cc/y0sfm95gv/prince_f.jpg);"></div>
    <span class="card-media-object-tag subtle">Selling Fast</span>
    <ul class="card-media-object-social-list">
      <li>
        <img src="https://s10.postimg.cc/3rjjbzcvd/profile_f.jpg" class="">
      </li>
      <li>
        <img src="https://s16.postimg.cc/b0j0djh79/profile_0_f.jpg" class="">
      </li>
      <li class="card-media-object-social-list-item-additional">
        <span>+2</span>
      </li>
    </ul>
  </div>
  <!-- body container -->
  <div class="card-media-body">
    <div class="card-media-body-top">
      <span class="subtle">Mon, APR 09, 7:00 PM</span>
      <div class="card-media-body-top-icons u-float-right">
        <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 0h24v24H0z" fill="none"/>
          <path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z"/>
        </svg>
        <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
          <path d="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"/>
          <path d="M0 0h24v24H0z" fill="none"/>
        </svg>
      </div>
    </div>
    <span class="card-media-body-heading">This Thing Called Life: A Celebration of Prince and His Legacy at MEZZANINE SF</span>
    <div class="card-media-body-supporting-bottom">
      <span class="card-media-body-supporting-bottom-text subtle">Mezzanine, San Francisco, CA</span>
      <span class="card-media-body-supporting-bottom-text subtle u-float-right">Free &ndash; $30</span>
    </div>
    <div class="card-media-body-supporting-bottom card-media-body-supporting-bottom-reveal">
      <span class="card-media-body-supporting-bottom-text subtle">#Music #Party</span>
      <a href="#/" class="card-media-body-supporting-bottom-text card-media-link u-float-right">VIEW TICKETS</a>
    </div>
  </div>
</div>
</div>
</div>

app/views/qols/show.html.erb
<div class="syousai-block">
 <h3>詳細</h3>
   <p><%= image_tag @qol.image_url, size: "250x200" if @qol.image? %></p>
   <p>店名 : <%= @qol.food %></p>
   <p>値段 : <%= @qol.cost %></p>
   <p>クーポン内容 : <%= @qol.coupon %></p>
   <p>アクセス : <%= @qol.place %></p>
   <p><%= @qol.created_at.to_s(:datetime_jp) %></p>

    <% if user_signed_in? %>
    <% if current_user.already_liked?(@qol) %>
      <%= link_to qol_like_path(@qol), method: :delete do %>
        <i class="fas fa-heart"></i><%= @qol.likes.count %>
       <% end %>
       <% else %>
       <%= link_to qol_likes_path(@qol), method: :post do %>
        <i class="far fa-heart"></i><%= @qol.likes.count %>
       <% end %>
    <% end %>
 <% else %>
   <i class="far fa-heart"></i><%= @qol.likes.count %>
 <% end %>



<h3>いいねしたユーザー</h3>
<% @qol.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <h3><p>コメント一覧</p></h3>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <div id='map'></div>

  <style>
  #map {
    height: 400px;
    width: 400px;
  }
  </style>
  
  <!-- js部分 -->
  <script>
      function initMap() {
  
        //初期表示位置
        let latlng = new google.maps.LatLng(38.60, 139.5);
        //デザイン
        let styles = [
             {
              stylers: [
               { "saturation": 0 },
               { "lightness": 0 }
              ]
             }
            ];
  
        let map = new google.maps.Map(document.getElementById('map'), {
            zoom: 5.5,
            styles: styles,
            center: latlng
        });
        let transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);
  
        //複数マーカー ここから
     
          ( function() { 
            let markerLatLng = new google.maps.LatLng({lat: <%= @qol.latitude %>, lng: <%= @qol.longitude %>}); // 緯度経度のデータ作成
            let marker = new google.maps.Marker({ 
              position: markerLatLng, 
              map: map 
            });
      　　　//マーカーをクリックしたとき、詳細情報を表示
            let infowindow = new google.maps.InfoWindow({
              position: markerLatLng,
              content: "<a href='<%= qol_url(@qol.id) %>' target='_blank'><%= @qol.food %></a>"
            }); //ここで詳細ページへのリンクを表示させる
            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
  
         })();
      
        //複数マーカー ここまで  
    }
  </script>
  
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
</div>

  <% if user_signed_in? %>
    <%= form_with(model: [@qol, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "編集する", edit_qol_path(@qol.id) %>
<%= link_to "安飯一覧に戻る", qols_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="profile-block">

<h3>プロフィール</h3>

<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>自己紹介 : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h3>ユーザーの投稿一覧</h3>
<% @user.qols.each do |t| %>
  <%= t.user.name %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.food %>
   <%= t.cost %>
   <%= t.coupon %>
   <%= t.place %>
   <%= t.created_at %>
<% end %>


<!-- 以下はいいね機能を実装している場合-->
<h3>ユーザーがいいねした投稿一覧</h3>
<% @user.liked_qols.each do |t| %>
  <%= t.user.name %>
  <%= t.food %>
   <%= t.cost %>
   <%= t.coupon %>
   <%= t.place %>
   <%= t.created_at %>
<% end %>
</div>


<%= link_to "安飯一覧に戻る", qols_path %>